### ISSUE TITLE
Size not set in MediaSourceInfo

### ISSUE THREAD

**Issue by konairius** [MediaBrowser/MediaBrowser#1007]
The field is not always set. It is documented as optional but there seems to be no Pattern on which Files have it and i didn't find any Documentation about it. I don't see any Reason why it should not be set for every Source.

**Comment by LukePulverenti** [comment]
It's normal. Internet channels may not have this information. Strm files will not have this information. Bluray/Dvd/Iso media info extraction may not have this information. Plain video files should have it but every once in a while there will be files that ffprobe fails to process.

**Comment by konairius** [comment]
Ok, I did a quick statistic on my library which is exclusively simple files and i got 1349 out of 10139.
I think somthing is going wrong there... Is there a way to force the size to be set (retry ffprobe or get it from somewhere else)

**Comment by LukePulverenti** [comment]
yes metadata manager refresh

**Comment by konairius** [comment]
Ok, thanks that seems to fix it
