### ISSUE TITLE
Segmented transcoding

### ISSUE THREAD

**Issue by jkaberg** [MediaBrowser/MediaBrowser#1015]
I'm seeing huge CPU usage (66% for 1 1080p stream!) on my i7 3770K, and I was wondering if something could be done? Obviously this doesn't hold up when several people wants to stream simultaneously. Plex solves this by segmenting the transcoding (for reference Plex can transcode 8 streams on the fly with 70-80% CPU usage on the very same CPU)

Forum related issues (quite recent ones aswell):
http://mediabrowser.tv/community/index.php?/topic/17300-mb3-on-freenas-high-cpu-usage-during-transcoding/
http://mediabrowser.tv/community/index.php?/topic/16745-segmenting-transcode/

I could output transcode logs if you want

-------------------------

Quoting a post on the forums: http://mediabrowser.tv/community/index.php?/topic/16745-segmenting-transcode/#entry163340

>Example of how mediabrowser works now;
>
>User 1 begins a transcode job, ffmpeg is spawned and use about 40-50% cpu until the full duration of the content is transcoded
>User 2 begins a transcode job same way as user 1, cpu is now almost maxed
>User 3 begins a transcode job, and everyone begins buffering
> 
>Now if this was done segmented, no buffering would accour
> 
>User 1 begins a transcode job, ffmpeg is spawned and transcodes a segment of 120 seconds, this is most likely done in 20-30 seconds
>User 2 begins a transcode job, ffmpeg is spawned and transcodes a segment of 120 seconds. User 1 has already transcoded 120 seconds, currently cpu is only occupied by user 2
>User 3 begins a transcode job while user 2's job is active. CPU is not maxed because 1  user isnt using any cpu, and user 2 and 3 are the only one currently transcoding.

**Comment by HLFH** [comment]
Any idea? Hi @LukePulverenti
