### ISSUE TITLE
readme file

### ISSUE THREAD

**Issue by splace** [MediaBrowser/MediaBrowser#1027]
is this really right?

"-v /etc/localtime:/etc/localtime:ro "

**Comment by LukePulverenti** [comment]
where is that from?

**Comment by splace** [comment]
the docker run command from the readme here;

https://github.com/MediaBrowser/MediaBrowser/tree/master/Docker

**Comment by LukePulverenti** [comment]
Yes as far as I know that's correct. I would post this in our community as our Docker maintainer is active there, as well as many of our Docker users. Thanks.
