### ISSUE TITLE
Clicking pause before video has started playing causes player to become unresponsive

### ISSUE THREAD

**Issue by tadams88** [MediaBrowser/MediaBrowser#1039]
Repro:
1. Play video
2. Prior to video beginning, click the pause button
3. Pause button does not become a play button, video does not play, pause button no longer does anything
4. Clicking the close button does not successfully close the video player. User is left with this:
![image](https://cloud.githubusercontent.com/assets/3075856/6653145/93cdbc16-ca43-11e4-9fc2-b37fac443b3a.png)

If user seeks to a new time in video, or clicks next/previous in playlist buttons the player resumes, and the close button functions as expected.

**Comment by LukePulverenti** [comment]
fixed with https://github.com/MediaBrowser/MediaBrowser/commit/e1167c0be9a11ed6832466622a002ae5a9c8e468
