### ISSUE TITLE
Why updating a list and don't use it after the update?

### ISSUE THREAD

**Issue by SvenVandenbrande** [MediaBrowser/MediaBrowser#1048]
Maybe it's for the future. But for performance.....

https://github.com/MediaBrowser/MediaBrowser/blob/master/MediaBrowser.Server.Implementations/Library/Validators/ArtistsValidator.cs#L71

https://github.com/MediaBrowser/MediaBrowser/blob/master/MediaBrowser.Server.Implementations/Playlists/PlaylistManager.cs#L192

https://github.com/MediaBrowser/MediaBrowser/blob/master/MediaBrowser.Server.Implementations/Sync/SyncManager.cs#L834

**Comment by LukePulverenti** [comment]
Thanks. These are just little mistakes.

**Comment by SvenVandenbrande** [comment]
No problem. Performance is everything. :)
I will search further for other Performance issues. :)
