### ISSUE TITLE
Turkish character problem with Roboto font family 

### ISSUE THREAD

**Issue by sgulci** [MediaBrowser/MediaBrowser#1057]
When i pick turkish language in emby server, there is a problem with font like this

![mb_font_problem](https://cloud.githubusercontent.com/assets/3424995/6880563/d3548006-d540-11e4-89bf-4bc532b16651.png)

if i deselect font family with chrome developer tool look llike this 

![mb_font_problem2](https://cloud.githubusercontent.com/assets/3424995/6880566/efea68c0-d540-11e4-9678-7939158844c7.png)

**Comment by LukePulverenti** [comment]
Fixed for next release.
