### ISSUE TITLE
[info] latest image works, Ubuntu 14.04.

### ISSUE THREAD

**Issue by splace** [MediaBrowser/MediaBrowser#1060]
(reporting this just for info, help people who might have had this, or if it reoccurs.)

latest image, 25320669c484  6 days ago , works fine.

virtually all previous, i tried at about 1 month intervals, images crashed during start-up.

except this image; 837dc1a86879, 7 months ago, that was functional.

ubuntu 14.04, 64bit, docker from repos.

**Comment by LukePulverenti** [comment]
Thanks!
