### ISSUE TITLE
Authorization Bypass in user settings

### ISSUE THREAD

**Issue by altf4** [MediaBrowser/MediaBrowser#1073]
User accounts which have had their authorization to modify settings revoked are able to change settings by forcefully browsing to the user settings page.

Emby administrators have the ability to remove a user's ability to modify their own settings. This is useful in instances where I would like to provide a shared read-only guest account to a group of friends. Since my friends are also hackers, however, I decided to poke at whether these settings actually worked.

Turns out that when an administrator revokes a user's authorization to modify account settings, it only removes the button from the user's interface. By manually browsing to the /mediabrowser/web/myprofile.html page, the "restricted" user can modify their settings. 

To reproduce:

As an administrator account, disable user settings for a user account, at the page: /mediabrowser/web/useredit.html, shown below:

![selection_004](https://cloud.githubusercontent.com/assets/609563/7100664/54fe5cd8-dfe3-11e4-9360-b67bc5d66aba.png)

Next, log into the Guest account and notice that the user preferences panel will have changed from appearing like this:

![selection_005](https://cloud.githubusercontent.com/assets/609563/7100670/c87b2dd0-dfe3-11e4-9851-3bc5e92cb2e7.png)

To now appear like this:

![selection_006](https://cloud.githubusercontent.com/assets/609563/7100673/e7ea6bd6-dfe3-11e4-9617-eb366c84b78a.png)

The Guest account in theory should now be locked down and unable to do things like change its own settings such as password. However, the Guest account can still access the settings page by manually browsing there:

your.server.ip.address:8096//mediabrowser/web/myprofile.html?userId=YOUR_USER_ID

You can view your user's current UserID by using the endpoint:
```
GET /mediabrowser/users
```

(Or indeed many other endpoints, UserIDs are not secrets)

![selection_007](https://cloud.githubusercontent.com/assets/609563/7100687/f0e3c52e-dfe4-11e4-91a8-b57df097fb49.png)

From here, the Guest account is able to make any settings changes, including changing the password (so that other users can't log in) or changing the avatar to something hilarious:

![selection_008](https://cloud.githubusercontent.com/assets/609563/7100693/21dbe350-dfe5-11e4-8451-234c73125e3d.png)

Thanks!

**Comment by altf4** [comment]
I should have said. I'm using:

Version 3.0.5518.7

**Comment by LukePulverenti** [comment]
Update to the latest version. There is still the issue of the html pages being accessible, but the api is secure and will reject any attempts to modify settings.
