### ISSUE TITLE
Release Date, Actual Date Added and MediaBrowsers "Date Added"

### ISSUE THREAD

**Issue by karbowiak** [MediaBrowser/MediaBrowser#1076]
Hi there, i'm currently having a weird problem.

The episode in question was released the 8th December 2014 (08-12-2014), and the actual date the episode was added was the 8th December 2014 (08-12-2014).

Now, MediaBrowser however, just randomly grabs a number from the ether, and sets Date Added as 01-10-2015.

And this isn't the only show it's doing it to, or item for that matter. It's happening to everything, Movies, TV Shows, Songs, etc.

OS: Debian Wheezy
MB Version: Latest Stable

And yes i tried both settings. "Use date scanned into the library" and "Use file creation date"
Both screw up the date added part equally bad. (Reinstalled and wiped MB's cache + settings + everything between each attempts)

**Comment by LukePulverenti** [comment]
There's nothing random. Either the date is coming from the filestamp, or you have a metadata file that contains the Added value. If you have the latter, then that is always used. If you have any other programs writing nfo files you will want to review.

**Comment by karbowiak** [comment]
fml.. You're right, it was the tvshow.nfo for Kodi that was doing it.

I was sure i had fixed that.. sigh..

Sorry for the inconvenience :P

**Comment by LukePulverenti** [comment]
Glad it is sorted :)
