### ISSUE TITLE
FFMpeg iTunes m4a transcode issue 

### ISSUE THREAD

**Issue by FoxUSA** [MediaBrowser/MediaBrowser#1101]
Hello,
Having issues playing itunes m4a(mp4) audio files through the html5 client. 

The files are decrypted and playable through other clients,

It looks like the root issue is the ffmpeg transcode command

```
/var/lib/mediabrowser/ffmpeg/20150331/ffmpeg -i file:"/media/data/users/Jake/Music/iTunes/iTunes Music/WALK THE MOON/TALKING IS HARD/03 Shut Up and Dance.m4a" -threads 0 -vn -ab 192000 -ac 5 -id3v2_version 3 -write_id3v1 1 -y "/var/lib/mediabrowser/transcoding-temp/b05880c2688481cd51509fc7c34668c8.mp3"
``` 
is what the logs show MediaBrowser is trying to run
ffmpeg returns a few errors
```
[libmp3lame @ 0x31c3000] Specified channel layout '5.0' is not supported
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```
If you run the above command with -ac 2 the transcode will complete

**Comment by LukePulverenti** [comment]
Thanks. Resolved for next release.
